=== alopgau/ALG-RecetasLMSGI/recetas.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="receta">
    <xs:attribute name="codigo" type="xs:integer">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombre"  type="xs:string"/>
        <xs:element name="categoria" type="xs:string"/>
        <xs:element name="tiempo"  type="xs:integer"/>
        <xs:element name="dificultad"    type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== alopgau/ALG-RecetasLMSGI/recetas.xml
<receta codigo="1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="recetas.xsd">
<nombre>Tortilla</nombre>
<categoria>Entrante<categoria>
<tiempo>10</tiempo>
<dificultad>Facil</dificultad>
</receta>
<receta codigo="2">
<nombre>Carne al toro</nombre>
<categoria>Principal<categoria>
<tiempo>25</tiempo>
<dificultad>Dificil</dificultad>
</receta>
<receta codigo="3">
<nombre>Helado</nombre>
<categoria>Postre<categoria>
<tiempo>15</tiempo>
<dificultad>Media</dificultad>
</receta>
</recetas>
